=== shixiaoshaguaya/eclipse-workspace/Java_Web/cz_javaWeb/bin/cz0915/Library.dtd
<!ELEMENT library (books,records)>
<!ELEMENT books (book+)>
<!ELEMENT book (title)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT records (item+)>
<!ELEMENT item (data,person)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT person EMPTY>
<!ATTLIST book bookid ID #REQUIRED>
<!ATTLIST person name CDATA #REQUIRED>
<!ATTLIST person borrowed IDREFS #REQUIRED>

=== shixiaoshaguaya/eclipse-workspace/Java_Web/cz_javaWeb/bin/cz0915/Library2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "Library.dtd">
<library>
	<books>
		<book bookid="b0101">
			<title>Java培训教材</title>
		</book>
		<book bookid="a0103">
			<title>Java Web开发</title>
		</book>
	</books>
	<records>
		<item>
			<data>2020-09-15</data>
			<person name="陈喆" borrowed="b0101 a0103" />
		</item>
	</records>
</library>
